project:
  type: website
  output-dir: _site

website:
  title: "Your Site Title"
  theme: jolla
  navbar:
    right:
      - text: "About"
        href: about.qmd

format:
  html:
    css: styles/site.scss
    toc: true
    toc-location: right
